//let mainApi = "https://d22h53uby2qjdr.cloudfront.net/";

let mainApi = 'https://r7hvl6uiue.execute-api.ap-south-1.amazonaws.com/dev/';
let mainApi1 = 'https://api.seetok.in/';
export const environment = {
    production: false,
    labmda_headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
    },
    images: {
        muteMicLink: '../assets/callPage/mute-mike.svg',
        muteVideoLink: '../assets/callPage/mute-video.svg',
        videoLink: '../assets/callPage/video.svg',
        micLink: '../assets/callPage/mike.svg',
        recieveUser: '/assets/dashboard/Recieve.svg',
        shareButtonLink: '../assets/callPage/screenshare.svg',
        unshareButtonLink: '../assets/callPage/unshare.svg',
    },
    messages: {
        cameraAlertHeader: 'Camera and microphone are blocked',
        cameraAlertMessage: `seetok requires access to camera and microphone.<br> Click the camera blocked icon in your browser's address bar.<br> Allow access and then refresh the page`,
        notificationHeader: 'Notification Status',
        notificationMessage:
            'Notification sent successfully. Wait for 3 minutes to send next notification',
        notificationMessageFailure:
            "Hey, you've already notified a user. Wait for 3 minutes to notify the next user",
    },

    razorkey: 'rzp_test_WgxFPjyVr9RkfS',
    agoraId: '5d6c356cefc04231be1a3980cd504f85',
    googleCred:
        '557497442643-nqav6tj7g3drro6hquen1ppoua3b87u4.apps.googleusercontent.com',
    SOCKET_ENDPOINT:
        'wss://fd301zqqd5.execute-api.ap-south-1.amazonaws.com/dev',
    list_users_url: mainApi + 'listhosts',
    //list_users_url: 'https://api.seetok.in/listhosts',
    createChannel: mainApi + 'createchannel',
    // createChannel:'https://api.seetok.in/createchannel',
    createSubmeeting: mainApi + 'createchannel',
    //sendrequests: mainApi + 'sendrequests',
    //endcall: mainApi + 'twiliohostavailable',

    myevents: mainApi + 'getmyevents',
    deleteEvent: mainApi + 'deletemyevent',
    editEvent: mainApi + 'updatemyevents',
    createEvent: mainApi + 'updateprofile',
    loginoauth: mainApi + 'oauthsignin',
    website_url: 'https://blynkspeak-toxc.web.app/home/hosts',
    facebook_url: 'http://www.facebook.com/sharer.php?u=',
    twitter_url: 'http://twitter.com/share?url=',
    linkedIn_url: 'http://www.linkedin.com/shareArticle?mini=true&url=',
    ratings: mainApi + 'ratings',
    makeonline: mainApi + 'makeonline',
    listrequests: mainApi + 'listrequests',
    loginpwd_url: mainApi + 'loginpassword',
    login_url: mainApi + 'loginemail',
    sendotp: mainApi + 'loginotp',
    register_mail: mainApi + 'registeremail',
    register_otp: mainApi + 'registerotp',
    register_pwd: mainApi + 'registerpassword',

    no_response: mainApi + 'updaterequeststatus',
    //reject_call: mainApi + 'rejectrequest',
    //reject_call: mainApi1 + 'rejectrequest',

    upload_image: mainApi + 'uploadprofileimage',
    timer: mainApi + 'timer',
    onlinestatus: mainApi + 'onlinestatus',
    logout: mainApi + 'logout',
    wallet_balance: mainApi + 'mybalance',
    username: mainApi + 'username',
    postedrequests: mainApi + 'postedrequests',
    getmeetingbyid: mainApi + 'getmeetingbyid',
    gethostbyeventid: mainApi + 'gethostbyeventid',
    updatehoststatus: mainApi + 'updatehoststatus',
    chooseactiveaccount: mainApi + 'chooseactiveaccount',
    getfield: mainApi + 'getnonverifiedfiled',
    forgototp: mainApi + 'forgetpasswordotp',
    forgotemail: mainApi + 'forgetpasswordemail',
    loginasguest: mainApi + 'loginasguest',
    //twilioChannel: mainApi + 'createchanneltwilio',

    twilioToken: mainApi + 'twilioaccesstoken',
    starttime: mainApi + 'updatemeetingtime',
    payUrl: mainApi + 'getpaymenturl',
    //payUrl: 'https://api.seetok.in/getpaymentlink',
    closeMeeting: mainApi + 'terminatechannel',
    addcredit: mainApi + 'addcredit',
    getEventById: mainApi + 'gethostbyeventid',
    myearning: mainApi + 'myearnings',
    incomingcalls: mainApi + 'incomingcalls',
    outgoingcalls: mainApi + 'outgoingcalls',
    missedcalls: mainApi + 'checkmissedcalls',
    gettenusers: mainApi + 'getlist',
    notifyuser: mainApi + 'notifyuser',
    publicKey:
        'BAAwuQ1mcJqAsDuxbsKgKoK6Kt2yI7xK_p3Izh8MiVmWNe4nS8lXy8caqdmxvm4ythra0pYRgqs2zqFUX5yjnb4',
    privateKey: 't5LZcxysvp9S6O9FaLBNG6fbP7URDzWalQAj1L4OYZg',
    notification: mainApi + 'notificationsubscription',
    //reject_call_user : mainApi + 'endrequest',
    reject_call_user: mainApi1 + 'endcall',
    check_request: mainApi1 + 'checkrequests',
    check_status: mainApi1 + 'checkrequeststatus',
    twilioChannel: mainApi1 + 'createchanneltwilio',
    reject_call: mainApi1 + 'rejectcall',
    sendrequests: mainApi1 + 'callhost',
    endcall: mainApi1 + 'hostavailable',
    filter: mainApi + 'filter',
};
